library(mapDK)

kommune_mapping <- c(
  'Nordborg' = 'Sønderborg',
  'Aalborg' = 'Aalborg',
  'Risskov' = 'Aarhus',
  'Skærbæk' = 'Tønder',
  'Ballerup' = 'Ballerup',
  'Kolding' = 'Kolding',
  'Kastrup' = 'Tårnby',
  'Hobro' = 'Mariagerfjord',
  'Dragør' = 'Dragør',
  'Næstved' = 'Næstved',
  'Varde' = 'Varde',
  'Haderslev' = 'Haderslev',
  'Kokkedal' = 'Fredensborg',
  'Storvorde' = 'Aalborg',
  'Frederikshavn' = 'Frederikshavn',
  'Sønderborg' = 'Sønderborg',
  'Fredericia' = 'Fredericia',
  'Hammel' = 'Favrskov',
  'Odense V' = 'Odense',
  'Søborg' = 'Gladsaxe',
  'Køge' = 'Køge',
  'Holbæk' = 'Holbæk',
  'Ringsted' = 'Ringsted',
  'Odense N' = 'Odense',
  'Frederiksværk' = 'Halsnæs',
  'Silkeborg' = 'Silkeborg',
  'Hjørring' = 'Hjørring',
  'Nykøbing M' = 'Morsø',
  'Højbjerg' = 'Aarhus',
  'Egå' = 'Aarhus',
  'Herning' = 'Herning',
  'Allerød' = 'Allerød',
  'Rask Mølle' = 'Hedensted',
  'Viborg' = 'Viborg',
  'Odense SV' = 'Odense',
  'Taastrup' = 'Høje-Taastrup',
  'Bramming' = 'Esbjerg',
  'Ringe' = 'Faaborg-Midtfyn',
  'Hillerød' = 'Hillerød',
  'Aarhus V' = 'Aarhus',
  'Roskilde' = 'Roskilde',
  'Svinninge' = 'Holbæk',
  'Agerskov' = 'Tønder',
  'Give' = 'Vejle',
  'Sulsted' = 'Aalborg',
  'Ry' = 'Skanderborg',
  'Ribe' = 'Esbjerg',
  'Ringkøbing' = 'Ringkøbing-Skjern',
  'Låsby' = 'Skanderborg',
  'Aars' = 'Vesthimmerland',
  'Tilst' = 'Aarhus',
  'Birkerød' = 'Rudersdal',
  'Slagelse' = 'Slagelse',
  'Kjellerup' = 'Silkeborg',
  'Glostrup' = 'Glostrup',
  'Ørbæk' = 'Nyborg',
  'Viby J' = 'Aarhus',
  'Vodskov' = 'Aalborg',
  'Daugård' = 'Hedensted',
  'Albertslund' = 'Albertslund',
  'Nykøbing F' = 'Guldborgsund',
  'Gentofte' = 'Gentofte',
  'Randers SV' = 'Randers',
  'Esbjerg Ø' = 'Esbjerg',
  'Lystrup' = 'Aarhus',
  'Blommenslyst' = 'Odense',
  'Holte' = 'Rudersdal',
  'Holstebro' = 'Holstebro',
  'Brønderslev' = 'Brønderslev',
  'Horsens' = 'Horsens',
  'Herlev' = 'Herlev',
  'København N' = 'København',
  'Haarby' = 'Assens',
  'Nørresundby' = 'Aalborg',
  'Grenaa' = 'Norddjurs',
  'Grindsted' = 'Billund',
  'Randers SØ' = 'Randers',
  'Skanderborg' = 'Skanderborg',
  'Vejen' = 'Vejen',
  'Sæby' = 'Frederikshavn',
  'Vejle' = 'Vejle',
  'Vejle Øst' = 'Vejle',
  'Esbjerg N' = 'Esbjerg',
  'Esbjerg V' = 'Esbjerg',
  'Rødovre' = 'Rødovre',
  'Hundested' = 'Halsnæs',
  'Lunderskov' = 'Kolding',
  'Bredebro' = 'Tønder',
  'Stenløse' = 'Egedal',
  'Hørsholm' = 'Hørsholm',
  'Hadsund' = 'Mariagerfjord',
  'Thisted' = 'Thisted',
  'Rødekro' = 'Aabenraa',
  'Ølstykke' = 'Egedal',
  'Odense NV' = 'Odense',
  'Tønder' = 'Tønder',
  'Hinnerup' = 'Favrskov',
  'Måløv' = 'Ballerup',
  'Farum' = 'Furesø',
  'Værløse' = 'Furesø',
  'Vanløse' = 'København',
  'Brøndby' = 'Brøndby',
  'Valby' = 'København',
  'København S' = 'København',
  'København Ø' = 'København',
  'København V' = 'København',
  'København NV' = 'København',
  'Frederiksberg' = 'Frederiksberg',
  'Aarhus N' = 'Aarhus',
  'Aarhus C' = 'Aarhus',
  'Brabrand' = 'Aarhus',
  'Tranbjerg J' = 'Aarhus',
  'Odense C' = 'Odense',
  'Odense M' = 'Odense',
  'Odense Ø' = 'Odense',
  'Svendborg' = 'Svendborg',
  'Esbjerg' = 'Esbjerg',
  'Randers' = 'Randers',
  'Ishøj' = 'Ishøj',
  'Karlslunde' = 'Greve',
  'Hedehusene' = 'Høje-Taastrup'
)
merged_df_final$kommune <- kommune_mapping[merged_df_final$city]

city_counts <- merged_df_final %>%
  group_by(kommune) %>%
  summarize(
    antal = n(),
    Gns_price = round(mean(price, na.rm = TRUE), digits = 0)
  )


mapDK(values = "antal", id = "kommune", data = city_counts)
sum(city_counts$antal)